export const fieldType = Object.freeze({
  RADIO: 'RadioButton',
  SELECT_BUTTON: 'SelectButton',
  RADIO_CUSTOM: 'RadioCustomButton',
  RADIO_INLINE: 'RadioInlineButton',
  CHECKBOX: 'CheckboxButton',
  CHECKBOX_CUSTOM: 'CheckboxCustomButton',
  INPUT_TEXT: 'InputText',
  INPUT_TEXT_AUTOCOMPLETE: 'InputTextAutocomplete',
  INPUT_MASK: 'InputMask',
  INPUT_DROPDOWN: 'InputDropdown',
  INPUT_DATE_PICKER: 'InputDatePicker',
  INPUT_UPLOAD: 'InputUpload',
  TEXT_AREA: 'TextArea',
  PASSWORD: 'InputTextHidden',
  INPUT_TEXT_SELECTABLE_OPTIONS: 'InputTextSelectableOptions',
  INPUT_TEXT_GROUP: 'InputTextGroup',
  SLIDER:'slider'
})
export const formFields = Object.freeze({
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  EMAIL: 'email',
  DATE_OF_BIRTH: 'dateOfBirth',
  PHONE_NUMBER: 'phoneNumber',
  USERNAME: 'username',
  PASSWORD: 'password',
  PASSWORD_REPEATED: 'passwordRepeat',
  PLACE_NAME:'placeName',
  PLACE_TYPE:'placeType',
  PLACE_DESC:'placeDescription',
  PLACE_WORKING_TIME_FROM:'placeWorkingTimeFrom',
  PLACE_WORKING_TIME_TO:'placeWorkingTimeTo',
  PLACE_LOCATION_LAT:'placeLocationLatitude',
  PLACE_LOCATION_LONG:'placeLocationLongitude',
  PLACE_LOCATION_COUNTRY:'placeLocationCountry',
  PLACE_LOCATION_CITY:'placeLocationCity',
  PLACE_LOCATION_STREET_NUMBER:'placeLocationStreetAndNumber',
  SEAT_TABLE_TYPE:'seatTableType',
  SEAT_TABLE_ID:'seatTableId',

  EVENT_PLACE_NAME:'eventPlaceName',
  EVENT_NAME:'eventName',
  EVENT_TYPE:'eventType',
  EVENT_DESC:'eventDescription',
  EVENT_TIME_FROM:'eventTimeFrom',
  EVENT_TIME_TO:'eventTimeTo',

  RESERVATION_TYPE_NAME:'reservationTypeName',
  RESERVATION_TYPE_PRICE:'reservationTypePrice',
  RESERVATION_TYPE_REMARK:'reservationTypeRemark',
  RESERVATION_TYPE_MAX_NUMBER_OF_GUESTS:'reservationTypeMaxNumberOfGuests',

  RESERVATION_NAME_ON:'reservationNameOn',
  RESERVATION_EMAIL:'reservationEmail',
  RESERVATION_NUMBER_OF_GUESTS:'reservationNumberOfGuests',



})
