export const applicationStore = Object.freeze({
  ERROR_MESSAGE: 'ERROR_MESSAGE',
  SPINNER_MESSAGE: 'SPINNER_MESSAGE',
  MESSAGE_MODAL_MESSAGE: 'MESSAGE_MODAL_MESSAGE',
  CAPTCHA_DATA: "CAPTCHA_DATA",
  SELECTED_SEAT_TABLE: 'selectedSeatTables',
  SELECTED_IMAGES: 'selectedImages',
  PLACE_DATA: "placeData",
  PLACE_IMAGES: "placeImages",
  PLACE_SEAT_TABLE: "placeSeatTable",
  PLACE_STAFF: "placeStaff",
  PLACE_EVENTS: "placeEvents",
  FOUND_EVENTS: "foundEvents",
  EVENT_PLACE_NAME_OPTIONS: 'eventPlaceNameOptions',
  SELECTED_EVENT_IMAGES: 'selectedEventImages',
  EVENT_DATA: 'eventData',
  EVENT_IMAGES: "eventImages",
  USER_ACTOR:"userActor",
  USER_ROLES:"userRoles",
  USER_DATA:"userData",
  SELECTED_RESERVATION_TYPE: 'selectedReservationType',
  SELECTED_EVENT_MAP:'selectedEventMap'
});